name: Vehicle-Test
options:
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 2 # indent by 2 spaces
  tabWidth: 2 # a tab is 2 spaces
  bundleIdPrefix: com.endava
  postGenCommand: pod update
  settingGroups:
commonBuildSettings:
  SWIFT_VERSION: 5
  CURRENT_PROJECT_VERSION: 1
  IPHONEOS_DEPLOYMENT_TARGET: 13.0
  SWIFT_OPTIMIZATION_LEVEL: -Onone
  TARGETED_DEVICE_FAMILY: '1'
  ENABLE_BITCODE: NO
  BUILD_LIBRARIES_FOR_DISTRIBUTION: YES
  CODE_SIGN_IDENTITY: "iPhone Developer"
  DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
targets: # The List of our targets
  Vehicle-Test:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
    - path: Vehicle-Test
    info:
      path: Vehicle-Test/Source/Info.plist
    dependencies:
      - target: Home
      - target: Api
      - target: CommonUI
      - target: Authentification
        embed : NO
        link : YES
  Home:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    ENABLE_BITCODE: NO
    sources:
    - path: Home
    dependencies:
      - target: CommonUI
      - target: Api
    info:
     path: Vehicle-Test/Source/Info.plist
  CommonUI:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    ENABLE_BITCODE: NO
    sources:
    - path: CommonUI
    groups:
    - commonBuildSettings
    info:
     path: Vehicle-Test/Source/Info.plist
  Api:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    ENABLE_BITCODE: NO
    sources:
    - path: Api
    groups:
    - commonBuildSettings
    info:
     path: Vehicle-Test/Source/Info.plist
  Authentification:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    sources:
    - path: Authentification
    dependencies:
      - target: CommonUI
      - target: Api
    info:
      path: Vehicle-Test/Source/Info.plist

 
